/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/full_adder_baseline.v:23.1-32.10" *)
module full_adder(a, b, cin, sum, cout);
  (* src = "rtl/full_adder_baseline.v:31.20-31.25" *)
  wire _00_;
  (* src = "rtl/full_adder_baseline.v:31.30-31.37" *)
  wire _01_;
  (* src = "rtl/full_adder_baseline.v:31.42-31.49" *)
  wire _02_;
  (* src = "rtl/full_adder_baseline.v:31.19-31.38" *)
  wire _03_;
  (* src = "rtl/full_adder_baseline.v:30.17-30.20" *)
  wire _04_;
  (* src = "rtl/full_adder_baseline.v:24.11-24.12" *)
  input a;
  wire a;
  (* src = "rtl/full_adder_baseline.v:25.11-25.12" *)
  input b;
  wire b;
  (* src = "rtl/full_adder_baseline.v:26.11-26.14" *)
  input cin;
  wire cin;
  (* src = "rtl/full_adder_baseline.v:28.12-28.16" *)
  output cout;
  wire cout;
  (* src = "rtl/full_adder_baseline.v:27.12-27.15" *)
  output sum;
  wire sum;
  assign _04_ = a ^(* src = "rtl/full_adder_baseline.v:30.17-30.20" *)  b;
  assign sum = _04_ ^(* src = "rtl/full_adder_baseline.v:30.17-30.24" *)  cin;
  assign _00_ = a &(* src = "rtl/full_adder_baseline.v:31.20-31.25" *)  b;
  assign _01_ = b &(* src = "rtl/full_adder_baseline.v:31.30-31.37" *)  cin;
  assign _03_ = _00_ |(* src = "rtl/full_adder_baseline.v:31.19-31.38" *)  _01_;
  assign _02_ = a &(* src = "rtl/full_adder_baseline.v:31.42-31.49" *)  cin;
  assign cout = _03_ |(* src = "rtl/full_adder_baseline.v:31.19-31.50" *)  _02_;
endmodule
