/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/full_adder_baseline.v:23.1-32.10" *)
module full_adder(a, b, cin, sum, cout);
  (* src = "rtl/full_adder_baseline.v:24.11-24.12" *)
  input a;
  wire a;
  (* src = "rtl/full_adder_baseline.v:25.11-25.12" *)
  input b;
  wire b;
  (* src = "rtl/full_adder_baseline.v:26.11-26.14" *)
  input cin;
  wire cin;
  (* src = "rtl/full_adder_baseline.v:28.12-28.16" *)
  output cout;
  wire cout;
  (* src = "rtl/full_adder_baseline.v:27.12-27.15" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__xor3_1 _0_ (
    .A(a),
    .B(b),
    .C(cin),
    .X(sum)
  );
  sky130_fd_sc_hd__maj3_1 _1_ (
    .A(a),
    .B(b),
    .C(cin),
    .X(cout)
  );
endmodule
